### ISSUE TITLE
Ownership of packages

### ISSUE THREAD

**Issue by cymerrad** [Crypto-Punkers/resolver-engine#102]
Shouldn't we finally change the default author and repository pointed by package.json's (multiple packages)?  
I suggest to introduce sth like:    
```
"repository": "git@github.com:Crypto-Punkers/resolver-engine.git",
"author": "Crypto Punkers <crypto@punkers.co>",
```

Also, mind the email above.

**Comment by ritave** [comment]
Sounds good. hello@punkers.co will work
