### ISSUE TITLE
Modify the way the tests are run

### ISSUE THREAD

**Issue by squadack** [Crypto-Punkers/resolver-engine#120]
Running `yarn test` should show full results of tests.
Currently, `yarn test` shows only summary of all tests grouped by package. If something goes wrong it's imposible to determine which test failed just by looking at that output. It would be useful to see what doesn't work - especially if we somehow manage to write code that fails only on CircleCI.

**Comment by ritave** [comment]
I've searched for alternative jest reporters, but the community around those seems to be lacking. The solution here would be to write a new jest reporter, but that is more code to support which is out of scope for this package.
Unless someone creates and maintains a better reporter for jest, I'd be happy to use it
